# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/krenehan/Documents/vivado_projects/pdp_test_proj/pdp_test_proj.srcs/sources_1/ip/fifo_generator_fpgatopc/fifo_generator_fpgatopc.xci
# IP: The module: 'fifo_generator_fpgatopc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/krenehan/Documents/vivado_projects/pdp_test_proj/pdp_test_proj.srcs/sources_1/ip/fifo_generator_fpgatopc/fifo_generator_fpgatopc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_fpgatopc'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/krenehan/Documents/vivado_projects/pdp_test_proj/pdp_test_proj.srcs/sources_1/ip/fifo_generator_fpgatopc/fifo_generator_fpgatopc_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_fpgatopc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/krenehan/Documents/vivado_projects/pdp_test_proj/pdp_test_proj.srcs/sources_1/ip/fifo_generator_fpgatopc/fifo_generator_fpgatopc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_fpgatopc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/krenehan/Documents/vivado_projects/pdp_test_proj/pdp_test_proj.srcs/sources_1/ip/fifo_generator_fpgatopc/fifo_generator_fpgatopc.xci
# IP: The module: 'fifo_generator_fpgatopc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/krenehan/Documents/vivado_projects/pdp_test_proj/pdp_test_proj.srcs/sources_1/ip/fifo_generator_fpgatopc/fifo_generator_fpgatopc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_fpgatopc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/krenehan/Documents/vivado_projects/pdp_test_proj/pdp_test_proj.srcs/sources_1/ip/fifo_generator_fpgatopc/fifo_generator_fpgatopc_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_fpgatopc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/krenehan/Documents/vivado_projects/pdp_test_proj/pdp_test_proj.srcs/sources_1/ip/fifo_generator_fpgatopc/fifo_generator_fpgatopc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_fpgatopc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
