webtalk_init -webtalk_dir C:/Users/ENVY/Google Drive/vivado_projects/pdp_test_proj/pdp_test_proj.sim/sim_1/behav/xsim/xsim.dir/encoder_decoder_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun May  5 04:06:47 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "53355636-18bb-43fb-bc50-ba2a0da93b6f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5444b9cd321141579400b0122d749eec" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "5 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "6" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.78_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "12684_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1056448411 -regid "" -xml C:/Users/ENVY/Google Drive/vivado_projects/pdp_test_proj/pdp_test_proj.sim/sim_1/behav/xsim/xsim.dir/encoder_decoder_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ENVY/Google Drive/vivado_projects/pdp_test_proj/pdp_test_proj.sim/sim_1/behav/xsim/xsim.dir/encoder_decoder_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ENVY/Google Drive/vivado_projects/pdp_test_proj/pdp_test_proj.sim/sim_1/behav/xsim/xsim.dir/encoder_decoder_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
