webtalk_init -webtalk_dir /u5/krenehan/vivado/pdp_test_proj/pdp_test_proj.sim/sim_1/behav/xsim/xsim.dir/relay_shift_register_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jul  2 02:49:50 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2489853" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "207312351_1777494964_210673932_226" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d307a0db-c24c-4a95-8f70-49b430bcb437" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5444b9cd321141579400b0122d749eec" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "77" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "RedHatEnterpriseWorkstation" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Red Hat Enterprise Linux Workstation release 6.10 (Santiago)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU           X5647  @ 2.93GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2926.143 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "203.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "6307837500 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "117856_KB" -context "xsim\\usage"
webtalk_transmit -clientid 128875173 -regid "207312351_1777494964_210673932_226" -xml /u5/krenehan/vivado/pdp_test_proj/pdp_test_proj.sim/sim_1/behav/xsim/xsim.dir/relay_shift_register_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /u5/krenehan/vivado/pdp_test_proj/pdp_test_proj.sim/sim_1/behav/xsim/xsim.dir/relay_shift_register_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /u5/krenehan/vivado/pdp_test_proj/pdp_test_proj.sim/sim_1/behav/xsim/xsim.dir/relay_shift_register_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
